name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # Triggers on tags like v1.0.0, v0.1.0, etc.

permissions:
  contents: write # Grants permission to create releases and upload assets

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # Adjust to your preferred Go version

      # Install dependencies
      - name: Install dependencies
        run: go get

      # Build for Linux
      - name: Build Linux binary
        run: GOOS=linux GOARCH=amd64 go build -o filemux-linux-amd64 filemux.go

      # Build for macOS
      - name: Build macOS binary
        run: GOOS=darwin GOARCH=amd64 go build -o filemux-darwin-amd64 filemux.go

      # Build for Windows
      - name: Build Windows binary
        run: GOOS=windows GOARCH=amd64 go build -o filemux-windows-amd64.exe filemux.go

      # Create Release and Upload Assets
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            filemux-linux-amd64
            filemux-darwin-amd64
            filemux-windows-amd64.exe
          prerelease: false
          draft: false